# Generated by Django 3.1.7 on 2021-02-27 18:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='book',
            name='link',
            field=models.CharField(default='', max_length=4000),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='book',
            name='photo',
            field=models.ImageField(default='', upload_to=''),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='book',
            name='price',
            field=models.FloatField(default=0),
            preserve_default=False,
        ),
    ]
